services:
    # mysql 8.1.0
    db:
        build: ./db
        networks:
            - back-net
        expose:
            - 3306
            - 33060

    # python 3.11
    api:
        build: ./api
        tty: true
        stdin_open: true
        networks:
            - front-net
            - back-net
        volumes:
            - app-vol:/tmp
        depends_on:
            - db
        expose:
            - 8000

    # python 3.11
    client:
        build: ./client
        command: /bin/bash
        tty: true
        stdin_open: true
        networks:
            - front-net
        volumes:
            - app-vol:/tmp
        depends_on:
            - api

networks:
    back-net:
    front-net:


volumes:
    app-vol:


