services:
    client:
        build: ./client
        networks:
            - app-net
        volumes:
            - app-vol:/shared
        depends_on:
            - db
        tty: true
        stdin_open: true

    db:
        build: ./db
        # command: '--default-authentication-plugin=mysql_native_password'
        # restart: on-failure
        # healthcheck:
        #     test:
        #         [
        #             'CMD-SHELL',
        #             'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-pswd)" --silent'
        #         ]
        #     interval: 3s
        #     retries: 5
        #     start_period: 30s
        networks:
            - app-net
        volumes:
            - app-vol:/shared
        expose:
            - 3306
            - 33060

networks:
    app-net:


volumes:
    app-vol:


