services:
    # mysql 8.1.0
    db:
        build: ./db
        networks:
            - app-net
        expose:
            - 3306
            - 33060

    # python 3.11
    api:
        build: ./api
        tty: true
        stdin_open: true
        networks:
            - app-net
        volumes:
            - app-vol:/tmp
        depends_on:
            - db
        expose:
            - 8000
            # - 3306
            # - 33060

            # python 3.11
    client:
        build: ./client
        command: /bin/bash
        tty: true
        stdin_open: true
        networks:
            - app-net
        volumes:
            - app-vol:/tmp
        depends_on:
            - api
        expose:
            - 8000

networks:
    app-net:


volumes:
    app-vol:


