services:

    # spark 3.3.3 python 3.8.10
    client:
        build: ./client
        command: /bin/bash
        tty: true
        stdin_open: true
        networks:
            - app-net
        volumes:
            - app-vol:/shared
        depends_on:
            - db
        expose:
            - 3306
            - 33060

    # mysql 8.1.0
    db:
        build: ./db
        networks:
            - app-net
        volumes:
            - app-vol:/shared
        expose:
            - 3306
            - 33060

networks:
    app-net:


volumes:
    app-vol:


