services:

    # spark 3.3.3 python 3.8.10
    api_server:
        build: ./api_server
        command: /bin/bash
        tty: true
        stdin_open: true
        networks:
            - app-net
        volumes:
            - app-vol:/tmp
        depends_on:
            - db
        expose:
            - 5000
            - 3306
            - 33060

    # mysql 8.1.0
    db:
        build: ./db
        networks:
            - app-net
        # volumes:
        #     - app-vol:/shared
        expose:
            - 3306
            - 33060

networks:
    app-net:


volumes:
    app-vol:

        # log
        # prevent writes of nulls
        # build:
        # api
        # update func
        # save to avro (keep n more recent backups or from last m days)
        # restore from avro
